name: Fuzz (Nightly)

on:
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch: {}

permissions: {}

jobs:
  fuzz:
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@b131ca5ebfca4930fe6d4a3e82d1e386b4873c94
        with:
          disable-sudo: true
          egress-policy: block
          allowed-endpoints: >
            api.github.com:443
            github.com:443
            golang.org:443
            objects.githubusercontent.com:443
            proxy.golang.org:443
            storage.googleapis.com:443
            sum.golang.org:443

      - name: Setup Go
        uses: bytemare/actions/init-go@dd05ea0e1ffbfa927a92264f3fd1f6182d2ba748

      - name: Run fuzzers (10 min)
        working-directory: .github
        env:
          GOFuzz: "1"
        run: |
          make FUZZTIME=10m

